FROM python:3.9-slim-buster

WORKDIR /usr/src/workspace/intuitiveweb-api

RUN apt-get update && \
    apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pymupdf==1.23.7 --pre

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD python ./src/main.py

EXPOSE 3002